### ISSUE TITLE
Can I use it with 'lit3'？

### ISSUE THREAD

**Issue by Jam1zhu** [fpipita/babel-plugin-css-tag-postcss#10]
I am using this library in `lit3` and encountering some issues. 
Is it a problem with my configuration?

### If I use it like this
```typescript
// variables.ts
import { css } from "lit";
export const textColor = `#343434`;

```

```typescript
// style.ts
import { css } from "lit";
import textColor from "./variables"
export default css`
button {
  color:${textColor}    
}
`;
```

```typescript
import { html } from "lit";
import { customElement } from "lit/decorators.js";
import styles from "./style";

@customElement('h-button')
class PageContainer extends LitElement {
  static styles = [styles];

  render() {
    return html`
        <button>button</button>
    `;
  }
}

```
#### The following error will occur
```
Unknown input options: entry. Allowed options: cache, context, experimentalCacheExpiry, experimentalLogSideEffects, external, input, logLevel, makeAbsoluteExternalsRelative, maxParallelFileOps, moduleContext, onLog, onwarn, perf, plugins, preserveEntrySignatures, preserveSymlinks, shimMissingExports, strictDeprecations, treeshake, watch
[babel] /my-path/components/_style/variables.ts: <css input>:1:1: Unknown word
file: /my-path/components/_style/variables.ts
error during build:
CssSyntaxError: /my-path/components/_style/variables.ts: <css input>:1:1: Unknown word
    at Input.error (/my-path/node_modules/.pnpm/postcss@8.4.33/node_modules/postcss/lib/input.js:106:16)
    at Parser.unknownWord (/my-path/node_modules/.pnpm/postcss@8.4.33/node_modules/postcss/lib/parser.js:594:22)
    at Parser.other (/my-path/node_modules/.pnpm/postcss@8.4.33/node_modules/postcss/lib/parser.js:436:12)
    at Parser.parse (/my-path/node_modules/.pnpm/postcss@8.4.33/node_modules/postcss/lib/parser.js:471:16)
    at parse (/my-path/node_modules/.pnpm/postcss@8.4.33/node_modules/postcss/lib/parse.js:11:12)
    at new LazyResult (/my-path/node_modules/.pnpm/postcss@8.4.33/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/my-path/node_modules/.pnpm/postcss@8.4.33/node_modules/postcss/lib/processor.js:53:14)
    at PluginPass.TaggedTemplateExpression (file:///my-path/node_modules/.pnpm/@fpipita+babel-plugin-css-tag-postcss@3.0.1_@babel+core@7.23.7_postcss@8.4.33/node_modules/@fpipita/babel-plugin-css-tag-postcss/src/babel-plugin-css-tag-postcss.js:47:31)
    at newFn (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/visitors.js:160:14)
    at NodePath._call (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:82:31)
    at TraversalContext.visitQueue (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at traverse (/pnpm-path/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/index.js:52:34)
    at transformFile (/pnpm-path/node_modules/.pnpm/@babel+core@7.23.7/node_modules/@babel/core/lib/transformation/index.js:82:31)
    at transformFile.next (<anonymous>)
    at run (/pnpm-path/node_modules/.pnpm/@babel+core@7.23.7/node_modules/@babel/core/lib/transformation/index.js:24:12)
    at run.next (<anonymous>)
    at transform (/pnpm-path/node_modules/.pnpm/@babel+core@7.23.7/node_modules/@babel/core/lib/transform.js:22:33)
    at transform.next (<anonymous>)
    at step (/pnpm-path/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:261:32)
    at /pnpm-path/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/pnpm-path/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:223:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by fpipita** [comment]
Hi, you're simply missing a semicolon in the css declaration:

```typescript
// style.ts
import { css } from "lit";
import textColor from "./variables"
export default css`
  button {
    color: ${textColor}; /* <- missing semicolon was here*/
  }
`;
 ```

Just as a matter of advice: although injecting`textColor` as a JavaScript variable is supported, it is best to use a CSS variable to fulfill this particular use case.
